/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Candidate {
    id: bigint;
    status: CandidateStatus;
    resume: string;
    pipelineLog: Array<PipelineTransition>;
    name: string;
    createdAt: Time;
    email: string;
    updatedAt: Time;
    experienceYears: bigint;
    phone: string;
    appliedJobIds: Array<bigint>;
    matchScores: Array<[bigint, bigint]>;
    skills: Array<string>;
}
export type Time = bigint;
export interface PipelineTransition {
    toStatus: CandidateStatus;
    note: string;
    fromStatus: CandidateStatus;
    timestamp: Time;
}
export interface AnalyticsResult {
    topScoringCandidates: Array<[bigint, bigint]>;
    totalOpenJobs: bigint;
    totalCandidatesPerJob: Array<[bigint, bigint]>;
    candidatesPerStage: Array<[string, bigint]>;
    averageTimeToHireDays: number;
}
export interface Interview {
    id: bigint;
    status: InterviewStatus;
    interviewer: string;
    jobId: bigint;
    interviewType: InterviewType;
    notes: string;
    dateTime: Time;
    candidateId: bigint;
}
export interface CommunicationTemplate {
    id: bigint;
    subject: string;
    body: string;
    name: string;
    category: string;
}
export interface ParsedResume {
    previousRoles: Array<string>;
    education: Array<string>;
    experienceYears: bigint;
    skills: Array<string>;
}
export interface JobRequisition {
    id: bigint;
    status: JobStatus;
    experienceLevel: bigint;
    title: string;
    jobType: JobType;
    createdAt: Time;
    description: string;
    department: string;
    requiredSkills: Array<string>;
    location: string;
}
export interface OfferLetter {
    id: bigint;
    status: OfferStatus;
    salary: number;
    createdAt: Time;
    jobId: bigint;
    letterText: string;
    clauses: string;
    candidateId: bigint;
    startDate: Time;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export enum CandidateStatus {
    new_ = "new",
    hired = "hired",
    offer = "offer",
    screening = "screening",
    interview = "interview",
    rejected = "rejected",
    shortlisted = "shortlisted"
}
export enum InterviewStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    completed = "completed"
}
export enum InterviewType {
    video = "video",
    phone = "phone",
    onSite = "onSite"
}
export enum JobStatus {
    closed = "closed",
    open = "open",
    draft = "draft",
    onHold = "onHold"
}
export enum JobType {
    contract = "contract",
    partTime = "partTime",
    fullTime = "fullTime"
}
export enum OfferStatus {
    pending = "pending",
    accepted = "accepted",
    declined = "declined"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Apply a candidate to a job. Any authenticated user.
     */
    applyToJob(candidateId: bigint, jobId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Calculate and store a match score for a candidate against a job. Any authenticated user.
     */
    calculateMatchScore(candidateId: bigint, jobId: bigint): Promise<bigint>;
    /**
     * / Create a candidate profile. Any authenticated user (recruiter submitting on behalf).
     */
    createCandidate(name: string, email: string, phone: string, resume: string, skills: Array<string>, experienceYears: bigint): Promise<bigint>;
    /**
     * / Create an interview record. Any authenticated user.
     */
    createInterview(candidateId: bigint, jobId: bigint, dateTime: Time, interviewer: string, interviewType: InterviewType, notes: string): Promise<bigint>;
    /**
     * / Create a new job requisition. Admin only.
     */
    createJob(title: string, department: string, location: string, jobType: JobType, description: string, requiredSkills: Array<string>, experienceLevel: bigint): Promise<bigint>;
    /**
     * / Generate and store an offer letter. Any authenticated user (recruiter).
     */
    createOfferLetter(candidateId: bigint, jobId: bigint, salary: number, startDate: Time, clauses: string): Promise<bigint>;
    /**
     * / Create a communication template. Admin only.
     */
    createTemplate(name: string, subject: string, body: string, category: string): Promise<bigint>;
    /**
     * / Delete a candidate. Admin only.
     */
    deleteCandidate(id: bigint): Promise<void>;
    /**
     * / Delete an interview. Admin only.
     */
    deleteInterview(id: bigint): Promise<void>;
    /**
     * / Delete a job requisition. Admin only.
     */
    deleteJob(id: bigint): Promise<void>;
    /**
     * / Delete an offer letter. Admin only.
     */
    deleteOfferLetter(id: bigint): Promise<void>;
    /**
     * / Delete a communication template. Admin only.
     */
    deleteTemplate(id: bigint): Promise<void>;
    /**
     * / Get recruiter analytics. Any authenticated user.
     */
    getAnalytics(): Promise<AnalyticsResult>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Get a single candidate. Any authenticated user.
     */
    getCandidate(id: bigint): Promise<Candidate | null>;
    /**
     * / Get candidates by job ID. Any authenticated user.
     */
    getCandidatesByJob(jobId: bigint): Promise<Array<Candidate>>;
    /**
     * / Get candidates by pipeline stage for a given job. Any authenticated user.
     */
    getCandidatesByStage(jobId: bigint, stage: CandidateStatus): Promise<Array<Candidate>>;
    /**
     * / Get a single interview. Any authenticated user.
     */
    getInterview(id: bigint): Promise<Interview | null>;
    /**
     * / List interviews for a candidate. Any authenticated user.
     */
    getInterviewsByCandidate(candidateId: bigint): Promise<Array<Interview>>;
    /**
     * / Get a single job requisition. Any authenticated user.
     */
    getJob(id: bigint): Promise<JobRequisition | null>;
    /**
     * / Get an offer letter. Any authenticated user.
     */
    getOfferLetter(id: bigint): Promise<OfferLetter | null>;
    /**
     * / List offer letters for a candidate. Any authenticated user.
     */
    getOffersByCandidate(candidateId: bigint): Promise<Array<OfferLetter>>;
    /**
     * / Get a single template. Any authenticated user.
     */
    getTemplate(id: bigint): Promise<CommunicationTemplate | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List all candidates. Any authenticated user.
     */
    listCandidates(): Promise<Array<Candidate>>;
    /**
     * / List all job requisitions. Any authenticated user.
     */
    listJobs(): Promise<Array<JobRequisition>>;
    /**
     * / List all templates. Any authenticated user.
     */
    listTemplates(): Promise<Array<CommunicationTemplate>>;
    /**
     * / Move a candidate to the next pipeline stage. Recruiter (user) or Admin only.
     */
    moveCandidateStage(candidateId: bigint, newStatus: CandidateStatus, note: string): Promise<void>;
    /**
     * / Parse a resume text and extract structured data. No auth required (public utility).
     */
    parseResume(resumeText: string): Promise<ParsedResume>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / Update candidate details. Any authenticated user.
     */
    updateCandidate(id: bigint, name: string, email: string, phone: string, resume: string, skills: Array<string>, experienceYears: bigint): Promise<void>;
    /**
     * / Update an interview record. Any authenticated user.
     */
    updateInterview(id: bigint, dateTime: Time, interviewer: string, interviewType: InterviewType, status: InterviewStatus, notes: string): Promise<void>;
    /**
     * / Update an existing job requisition. Admin only.
     */
    updateJob(id: bigint, title: string, department: string, location: string, jobType: JobType, description: string, requiredSkills: Array<string>, experienceLevel: bigint): Promise<void>;
    /**
     * / Update job status. Admin only.
     */
    updateJobStatus(id: bigint, status: JobStatus): Promise<void>;
    /**
     * / Update offer letter status. Any authenticated user.
     */
    updateOfferStatus(id: bigint, status: OfferStatus): Promise<void>;
    /**
     * / Update a communication template. Admin only.
     */
    updateTemplate(id: bigint, name: string, subject: string, body: string, category: string): Promise<void>;
}
import type { Candidate as _Candidate, CandidateStatus as _CandidateStatus, CommunicationTemplate as _CommunicationTemplate, Interview as _Interview, InterviewStatus as _InterviewStatus, InterviewType as _InterviewType, JobRequisition as _JobRequisition, JobStatus as _JobStatus, JobType as _JobType, OfferLetter as _OfferLetter, OfferStatus as _OfferStatus, PipelineTransition as _PipelineTransition, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async applyToJob(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyToJob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyToJob(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateMatchScore(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateMatchScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateMatchScore(arg0, arg1);
            return result;
        }
    }
    async createCandidate(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCandidate(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCandidate(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createInterview(arg0: bigint, arg1: bigint, arg2: Time, arg3: string, arg4: InterviewType, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInterview(arg0, arg1, arg2, arg3, to_candid_InterviewType_n3(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInterview(arg0, arg1, arg2, arg3, to_candid_InterviewType_n3(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async createJob(arg0: string, arg1: string, arg2: string, arg3: JobType, arg4: string, arg5: Array<string>, arg6: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(arg0, arg1, arg2, to_candid_JobType_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(arg0, arg1, arg2, to_candid_JobType_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async createOfferLetter(arg0: bigint, arg1: bigint, arg2: number, arg3: Time, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOfferLetter(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOfferLetter(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createTemplate(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTemplate(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTemplate(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteCandidate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCandidate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCandidate(arg0);
            return result;
        }
    }
    async deleteInterview(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInterview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInterview(arg0);
            return result;
        }
    }
    async deleteJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async deleteOfferLetter(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOfferLetter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOfferLetter(arg0);
            return result;
        }
    }
    async deleteTemplate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTemplate(arg0);
            return result;
        }
    }
    async getAnalytics(): Promise<AnalyticsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidate(arg0: bigint): Promise<Candidate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidate(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidate(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidatesByJob(arg0: bigint): Promise<Array<Candidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidatesByJob(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidatesByJob(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidatesByStage(arg0: bigint, arg1: CandidateStatus): Promise<Array<Candidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidatesByStage(arg0, to_candid_CandidateStatus_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidatesByStage(arg0, to_candid_CandidateStatus_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInterview(arg0: bigint): Promise<Interview | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterview(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterview(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInterviewsByCandidate(arg0: bigint): Promise<Array<Interview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterviewsByCandidate(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterviewsByCandidate(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: bigint): Promise<JobRequisition | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfferLetter(arg0: bigint): Promise<OfferLetter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfferLetter(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfferLetter(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOffersByCandidate(arg0: bigint): Promise<Array<OfferLetter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOffersByCandidate(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOffersByCandidate(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTemplate(arg0: bigint): Promise<CommunicationTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplate(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplate(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCandidates(): Promise<Array<Candidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCandidates();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCandidates();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async listJobs(): Promise<Array<JobRequisition>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobs();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobs();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTemplates(): Promise<Array<CommunicationTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTemplates();
            return result;
        }
    }
    async moveCandidateStage(arg0: bigint, arg1: CandidateStatus, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moveCandidateStage(arg0, to_candid_CandidateStatus_n19(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveCandidateStage(arg0, to_candid_CandidateStatus_n19(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async parseResume(arg0: string): Promise<ParsedResume> {
        if (this.processError) {
            try {
                const result = await this.actor.parseResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.parseResume(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCandidate(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCandidate(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCandidate(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateInterview(arg0: bigint, arg1: Time, arg2: string, arg3: InterviewType, arg4: InterviewStatus, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInterview(arg0, arg1, arg2, to_candid_InterviewType_n3(this._uploadFile, this._downloadFile, arg3), to_candid_InterviewStatus_n44(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInterview(arg0, arg1, arg2, to_candid_InterviewType_n3(this._uploadFile, this._downloadFile, arg3), to_candid_InterviewStatus_n44(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateJob(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: JobType, arg5: string, arg6: Array<string>, arg7: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, to_candid_JobType_n5(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, to_candid_JobType_n5(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7);
            return result;
        }
    }
    async updateJobStatus(arg0: bigint, arg1: JobStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobStatus(arg0, to_candid_JobStatus_n46(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobStatus(arg0, to_candid_JobStatus_n46(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOfferStatus(arg0: bigint, arg1: OfferStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOfferStatus(arg0, to_candid_OfferStatus_n48(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOfferStatus(arg0, to_candid_OfferStatus_n48(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTemplate(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTemplate(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTemplate(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_CandidateStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CandidateStatus): CandidateStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Candidate_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Candidate): Candidate {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_InterviewStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterviewStatus): InterviewStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_InterviewType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterviewType): InterviewType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Interview_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Interview): Interview {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_JobRequisition_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobRequisition): JobRequisition {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_JobType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_OfferLetter_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OfferLetter): OfferLetter {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_OfferStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OfferStatus): OfferStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_PipelineTransition_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PipelineTransition): PipelineTransition {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Candidate]): Candidate | null {
    return value.length === 0 ? null : from_candid_Candidate_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Interview]): Interview | null {
    return value.length === 0 ? null : from_candid_Interview_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobRequisition]): JobRequisition | null {
    return value.length === 0 ? null : from_candid_JobRequisition_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OfferLetter]): OfferLetter | null {
    return value.length === 0 ? null : from_candid_OfferLetter_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CommunicationTemplate]): CommunicationTemplate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CandidateStatus;
    resume: string;
    pipelineLog: Array<_PipelineTransition>;
    name: string;
    createdAt: _Time;
    email: string;
    updatedAt: _Time;
    experienceYears: bigint;
    phone: string;
    appliedJobIds: Array<bigint>;
    matchScores: Array<[bigint, bigint]>;
    skills: Array<string>;
}): {
    id: bigint;
    status: CandidateStatus;
    resume: string;
    pipelineLog: Array<PipelineTransition>;
    name: string;
    createdAt: Time;
    email: string;
    updatedAt: Time;
    experienceYears: bigint;
    phone: string;
    appliedJobIds: Array<bigint>;
    matchScores: Array<[bigint, bigint]>;
    skills: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_CandidateStatus_n13(_uploadFile, _downloadFile, value.status),
        resume: value.resume,
        pipelineLog: from_candid_vec_n15(_uploadFile, _downloadFile, value.pipelineLog),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        experienceYears: value.experienceYears,
        phone: value.phone,
        appliedJobIds: value.appliedJobIds,
        matchScores: value.matchScores,
        skills: value.skills
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    toStatus: _CandidateStatus;
    note: string;
    fromStatus: _CandidateStatus;
    timestamp: _Time;
}): {
    toStatus: CandidateStatus;
    note: string;
    fromStatus: CandidateStatus;
    timestamp: Time;
} {
    return {
        toStatus: from_candid_CandidateStatus_n13(_uploadFile, _downloadFile, value.toStatus),
        note: value.note,
        fromStatus: from_candid_CandidateStatus_n13(_uploadFile, _downloadFile, value.fromStatus),
        timestamp: value.timestamp
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _InterviewStatus;
    interviewer: string;
    jobId: bigint;
    interviewType: _InterviewType;
    notes: string;
    dateTime: _Time;
    candidateId: bigint;
}): {
    id: bigint;
    status: InterviewStatus;
    interviewer: string;
    jobId: bigint;
    interviewType: InterviewType;
    notes: string;
    dateTime: Time;
    candidateId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_InterviewStatus_n24(_uploadFile, _downloadFile, value.status),
        interviewer: value.interviewer,
        jobId: value.jobId,
        interviewType: from_candid_InterviewType_n26(_uploadFile, _downloadFile, value.interviewType),
        notes: value.notes,
        dateTime: value.dateTime,
        candidateId: value.candidateId
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _JobStatus;
    experienceLevel: bigint;
    title: string;
    jobType: _JobType;
    createdAt: _Time;
    description: string;
    department: string;
    requiredSkills: Array<string>;
    location: string;
}): {
    id: bigint;
    status: JobStatus;
    experienceLevel: bigint;
    title: string;
    jobType: JobType;
    createdAt: Time;
    description: string;
    department: string;
    requiredSkills: Array<string>;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n32(_uploadFile, _downloadFile, value.status),
        experienceLevel: value.experienceLevel,
        title: value.title,
        jobType: from_candid_JobType_n34(_uploadFile, _downloadFile, value.jobType),
        createdAt: value.createdAt,
        description: value.description,
        department: value.department,
        requiredSkills: value.requiredSkills,
        location: value.location
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OfferStatus;
    salary: number;
    createdAt: _Time;
    jobId: bigint;
    letterText: string;
    clauses: string;
    candidateId: bigint;
    startDate: _Time;
}): {
    id: bigint;
    status: OfferStatus;
    salary: number;
    createdAt: Time;
    jobId: bigint;
    letterText: string;
    clauses: string;
    candidateId: bigint;
    startDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_OfferStatus_n39(_uploadFile, _downloadFile, value.status),
        salary: value.salary,
        createdAt: value.createdAt,
        jobId: value.jobId,
        letterText: value.letterText,
        clauses: value.clauses,
        candidateId: value.candidateId,
        startDate: value.startDate
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    hired: null;
} | {
    offer: null;
} | {
    screening: null;
} | {
    interview: null;
} | {
    rejected: null;
} | {
    shortlisted: null;
}): CandidateStatus {
    return "new" in value ? CandidateStatus.new : "hired" in value ? CandidateStatus.hired : "offer" in value ? CandidateStatus.offer : "screening" in value ? CandidateStatus.screening : "interview" in value ? CandidateStatus.interview : "rejected" in value ? CandidateStatus.rejected : "shortlisted" in value ? CandidateStatus.shortlisted : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): InterviewStatus {
    return "scheduled" in value ? InterviewStatus.scheduled : "cancelled" in value ? InterviewStatus.cancelled : "completed" in value ? InterviewStatus.completed : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    phone: null;
} | {
    onSite: null;
}): InterviewType {
    return "video" in value ? InterviewType.video : "phone" in value ? InterviewType.phone : "onSite" in value ? InterviewType.onSite : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    draft: null;
} | {
    onHold: null;
}): JobStatus {
    return "closed" in value ? JobStatus.closed : "open" in value ? JobStatus.open : "draft" in value ? JobStatus.draft : "onHold" in value ? JobStatus.onHold : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
}): JobType {
    return "contract" in value ? JobType.contract : "partTime" in value ? JobType.partTime : "fullTime" in value ? JobType.fullTime : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    accepted: null;
} | {
    declined: null;
}): OfferStatus {
    return "pending" in value ? OfferStatus.pending : "accepted" in value ? OfferStatus.accepted : "declined" in value ? OfferStatus.declined : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PipelineTransition>): Array<PipelineTransition> {
    return value.map((x)=>from_candid_PipelineTransition_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Candidate>): Array<Candidate> {
    return value.map((x)=>from_candid_Candidate_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Interview>): Array<Interview> {
    return value.map((x)=>from_candid_Interview_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OfferLetter>): Array<OfferLetter> {
    return value.map((x)=>from_candid_OfferLetter_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobRequisition>): Array<JobRequisition> {
    return value.map((x)=>from_candid_JobRequisition_n30(_uploadFile, _downloadFile, x));
}
function to_candid_CandidateStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CandidateStatus): _CandidateStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_InterviewStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterviewStatus): _InterviewStatus {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_InterviewType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterviewType): _InterviewType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_JobStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_JobType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_OfferStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OfferStatus): _OfferStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CandidateStatus): {
    new: null;
} | {
    hired: null;
} | {
    offer: null;
} | {
    screening: null;
} | {
    interview: null;
} | {
    rejected: null;
} | {
    shortlisted: null;
} {
    return value == CandidateStatus.new ? {
        new_: null
    } : value == CandidateStatus.hired ? {
        hired: null
    } : value == CandidateStatus.offer ? {
        offer: null
    } : value == CandidateStatus.screening ? {
        screening: null
    } : value == CandidateStatus.interview ? {
        interview: null
    } : value == CandidateStatus.rejected ? {
        rejected: null
    } : value == CandidateStatus.shortlisted ? {
        shortlisted: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterviewType): {
    video: null;
} | {
    phone: null;
} | {
    onSite: null;
} {
    return value == InterviewType.video ? {
        video: null
    } : value == InterviewType.phone ? {
        phone: null
    } : value == InterviewType.onSite ? {
        onSite: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterviewStatus): {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} {
    return value == InterviewStatus.scheduled ? {
        scheduled: null
    } : value == InterviewStatus.cancelled ? {
        cancelled: null
    } : value == InterviewStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    closed: null;
} | {
    open: null;
} | {
    draft: null;
} | {
    onHold: null;
} {
    return value == JobStatus.closed ? {
        closed: null
    } : value == JobStatus.open ? {
        open: null
    } : value == JobStatus.draft ? {
        draft: null
    } : value == JobStatus.onHold ? {
        onHold: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OfferStatus): {
    pending: null;
} | {
    accepted: null;
} | {
    declined: null;
} {
    return value == OfferStatus.pending ? {
        pending: null
    } : value == OfferStatus.accepted ? {
        accepted: null
    } : value == OfferStatus.declined ? {
        declined: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
} {
    return value == JobType.contract ? {
        contract: null
    } : value == JobType.partTime ? {
        partTime: null
    } : value == JobType.fullTime ? {
        fullTime: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
