/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const InterviewType = IDL.Variant({
  'video' : IDL.Null,
  'phone' : IDL.Null,
  'onSite' : IDL.Null,
});
export const JobType = IDL.Variant({
  'contract' : IDL.Null,
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
});
export const AnalyticsResult = IDL.Record({
  'topScoringCandidates' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'totalOpenJobs' : IDL.Nat,
  'totalCandidatesPerJob' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'candidatesPerStage' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'averageTimeToHireDays' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const CandidateStatus = IDL.Variant({
  'new' : IDL.Null,
  'hired' : IDL.Null,
  'offer' : IDL.Null,
  'screening' : IDL.Null,
  'interview' : IDL.Null,
  'rejected' : IDL.Null,
  'shortlisted' : IDL.Null,
});
export const PipelineTransition = IDL.Record({
  'toStatus' : CandidateStatus,
  'note' : IDL.Text,
  'fromStatus' : CandidateStatus,
  'timestamp' : Time,
});
export const Candidate = IDL.Record({
  'id' : IDL.Nat,
  'status' : CandidateStatus,
  'resume' : IDL.Text,
  'pipelineLog' : IDL.Vec(PipelineTransition),
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'updatedAt' : Time,
  'experienceYears' : IDL.Nat,
  'phone' : IDL.Text,
  'appliedJobIds' : IDL.Vec(IDL.Nat),
  'matchScores' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'skills' : IDL.Vec(IDL.Text),
});
export const InterviewStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Interview = IDL.Record({
  'id' : IDL.Nat,
  'status' : InterviewStatus,
  'interviewer' : IDL.Text,
  'jobId' : IDL.Nat,
  'interviewType' : InterviewType,
  'notes' : IDL.Text,
  'dateTime' : Time,
  'candidateId' : IDL.Nat,
});
export const JobStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'draft' : IDL.Null,
  'onHold' : IDL.Null,
});
export const JobRequisition = IDL.Record({
  'id' : IDL.Nat,
  'status' : JobStatus,
  'experienceLevel' : IDL.Nat,
  'title' : IDL.Text,
  'jobType' : JobType,
  'createdAt' : Time,
  'description' : IDL.Text,
  'department' : IDL.Text,
  'requiredSkills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const OfferStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const OfferLetter = IDL.Record({
  'id' : IDL.Nat,
  'status' : OfferStatus,
  'salary' : IDL.Float64,
  'createdAt' : Time,
  'jobId' : IDL.Nat,
  'letterText' : IDL.Text,
  'clauses' : IDL.Text,
  'candidateId' : IDL.Nat,
  'startDate' : Time,
});
export const CommunicationTemplate = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'name' : IDL.Text,
  'category' : IDL.Text,
});
export const ParsedResume = IDL.Record({
  'previousRoles' : IDL.Vec(IDL.Text),
  'education' : IDL.Vec(IDL.Text),
  'experienceYears' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToJob' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateMatchScore' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'createCandidate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createInterview' : IDL.Func(
      [IDL.Nat, IDL.Nat, Time, IDL.Text, InterviewType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        JobType,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'createOfferLetter' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Float64, Time, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createTemplate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteCandidate' : IDL.Func([IDL.Nat], [], []),
  'deleteInterview' : IDL.Func([IDL.Nat], [], []),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'deleteOfferLetter' : IDL.Func([IDL.Nat], [], []),
  'deleteTemplate' : IDL.Func([IDL.Nat], [], []),
  'getAnalytics' : IDL.Func([], [AnalyticsResult], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidate' : IDL.Func([IDL.Nat], [IDL.Opt(Candidate)], ['query']),
  'getCandidatesByJob' : IDL.Func([IDL.Nat], [IDL.Vec(Candidate)], ['query']),
  'getCandidatesByStage' : IDL.Func(
      [IDL.Nat, CandidateStatus],
      [IDL.Vec(Candidate)],
      ['query'],
    ),
  'getInterview' : IDL.Func([IDL.Nat], [IDL.Opt(Interview)], ['query']),
  'getInterviewsByCandidate' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Interview)],
      ['query'],
    ),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(JobRequisition)], ['query']),
  'getOfferLetter' : IDL.Func([IDL.Nat], [IDL.Opt(OfferLetter)], ['query']),
  'getOffersByCandidate' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(OfferLetter)],
      ['query'],
    ),
  'getTemplate' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CommunicationTemplate)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
  'listJobs' : IDL.Func([], [IDL.Vec(JobRequisition)], ['query']),
  'listTemplates' : IDL.Func([], [IDL.Vec(CommunicationTemplate)], ['query']),
  'moveCandidateStage' : IDL.Func([IDL.Nat, CandidateStatus, IDL.Text], [], []),
  'parseResume' : IDL.Func([IDL.Text], [ParsedResume], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCandidate' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateInterview' : IDL.Func(
      [IDL.Nat, Time, IDL.Text, InterviewType, InterviewStatus, IDL.Text],
      [],
      [],
    ),
  'updateJob' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        JobType,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateJobStatus' : IDL.Func([IDL.Nat, JobStatus], [], []),
  'updateOfferStatus' : IDL.Func([IDL.Nat, OfferStatus], [], []),
  'updateTemplate' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const InterviewType = IDL.Variant({
    'video' : IDL.Null,
    'phone' : IDL.Null,
    'onSite' : IDL.Null,
  });
  const JobType = IDL.Variant({
    'contract' : IDL.Null,
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
  });
  const AnalyticsResult = IDL.Record({
    'topScoringCandidates' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'totalOpenJobs' : IDL.Nat,
    'totalCandidatesPerJob' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'candidatesPerStage' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'averageTimeToHireDays' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const CandidateStatus = IDL.Variant({
    'new' : IDL.Null,
    'hired' : IDL.Null,
    'offer' : IDL.Null,
    'screening' : IDL.Null,
    'interview' : IDL.Null,
    'rejected' : IDL.Null,
    'shortlisted' : IDL.Null,
  });
  const PipelineTransition = IDL.Record({
    'toStatus' : CandidateStatus,
    'note' : IDL.Text,
    'fromStatus' : CandidateStatus,
    'timestamp' : Time,
  });
  const Candidate = IDL.Record({
    'id' : IDL.Nat,
    'status' : CandidateStatus,
    'resume' : IDL.Text,
    'pipelineLog' : IDL.Vec(PipelineTransition),
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'updatedAt' : Time,
    'experienceYears' : IDL.Nat,
    'phone' : IDL.Text,
    'appliedJobIds' : IDL.Vec(IDL.Nat),
    'matchScores' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'skills' : IDL.Vec(IDL.Text),
  });
  const InterviewStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Interview = IDL.Record({
    'id' : IDL.Nat,
    'status' : InterviewStatus,
    'interviewer' : IDL.Text,
    'jobId' : IDL.Nat,
    'interviewType' : InterviewType,
    'notes' : IDL.Text,
    'dateTime' : Time,
    'candidateId' : IDL.Nat,
  });
  const JobStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'draft' : IDL.Null,
    'onHold' : IDL.Null,
  });
  const JobRequisition = IDL.Record({
    'id' : IDL.Nat,
    'status' : JobStatus,
    'experienceLevel' : IDL.Nat,
    'title' : IDL.Text,
    'jobType' : JobType,
    'createdAt' : Time,
    'description' : IDL.Text,
    'department' : IDL.Text,
    'requiredSkills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const OfferStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const OfferLetter = IDL.Record({
    'id' : IDL.Nat,
    'status' : OfferStatus,
    'salary' : IDL.Float64,
    'createdAt' : Time,
    'jobId' : IDL.Nat,
    'letterText' : IDL.Text,
    'clauses' : IDL.Text,
    'candidateId' : IDL.Nat,
    'startDate' : Time,
  });
  const CommunicationTemplate = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'name' : IDL.Text,
    'category' : IDL.Text,
  });
  const ParsedResume = IDL.Record({
    'previousRoles' : IDL.Vec(IDL.Text),
    'education' : IDL.Vec(IDL.Text),
    'experienceYears' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToJob' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateMatchScore' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'createCandidate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createInterview' : IDL.Func(
        [IDL.Nat, IDL.Nat, Time, IDL.Text, InterviewType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          JobType,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'createOfferLetter' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Float64, Time, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createTemplate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteCandidate' : IDL.Func([IDL.Nat], [], []),
    'deleteInterview' : IDL.Func([IDL.Nat], [], []),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'deleteOfferLetter' : IDL.Func([IDL.Nat], [], []),
    'deleteTemplate' : IDL.Func([IDL.Nat], [], []),
    'getAnalytics' : IDL.Func([], [AnalyticsResult], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidate' : IDL.Func([IDL.Nat], [IDL.Opt(Candidate)], ['query']),
    'getCandidatesByJob' : IDL.Func([IDL.Nat], [IDL.Vec(Candidate)], ['query']),
    'getCandidatesByStage' : IDL.Func(
        [IDL.Nat, CandidateStatus],
        [IDL.Vec(Candidate)],
        ['query'],
      ),
    'getInterview' : IDL.Func([IDL.Nat], [IDL.Opt(Interview)], ['query']),
    'getInterviewsByCandidate' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Interview)],
        ['query'],
      ),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(JobRequisition)], ['query']),
    'getOfferLetter' : IDL.Func([IDL.Nat], [IDL.Opt(OfferLetter)], ['query']),
    'getOffersByCandidate' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(OfferLetter)],
        ['query'],
      ),
    'getTemplate' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CommunicationTemplate)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
    'listJobs' : IDL.Func([], [IDL.Vec(JobRequisition)], ['query']),
    'listTemplates' : IDL.Func([], [IDL.Vec(CommunicationTemplate)], ['query']),
    'moveCandidateStage' : IDL.Func(
        [IDL.Nat, CandidateStatus, IDL.Text],
        [],
        [],
      ),
    'parseResume' : IDL.Func([IDL.Text], [ParsedResume], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCandidate' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateInterview' : IDL.Func(
        [IDL.Nat, Time, IDL.Text, InterviewType, InterviewStatus, IDL.Text],
        [],
        [],
      ),
    'updateJob' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          JobType,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateJobStatus' : IDL.Func([IDL.Nat, JobStatus], [], []),
    'updateOfferStatus' : IDL.Func([IDL.Nat, OfferStatus], [], []),
    'updateTemplate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };