/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsResult {
  'topScoringCandidates' : Array<[bigint, bigint]>,
  'totalOpenJobs' : bigint,
  'avgTimeToHirePerJob' : Array<[bigint, number]>,
  'totalCandidatesPerJob' : Array<[bigint, bigint]>,
  'last30DaysApplications' : Array<bigint>,
  'candidatesPerStage' : Array<[string, bigint]>,
  'topJobsByVolume' : Array<[bigint, bigint]>,
  'averageTimeToHireDays' : number,
  'pipelineStageDistribution' : Array<[string, bigint]>,
}
export interface Candidate {
  'id' : bigint,
  'status' : CandidateStatus,
  'resume' : string,
  'pipelineLog' : Array<PipelineTransition>,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'updatedAt' : Time,
  'experienceYears' : bigint,
  'phone' : string,
  'appliedJobIds' : Array<bigint>,
  'matchScores' : Array<[bigint, bigint]>,
  'skills' : Array<string>,
}
export type CandidateStatus = { 'new' : null } |
  { 'hired' : null } |
  { 'offer' : null } |
  { 'screening' : null } |
  { 'interview' : null } |
  { 'rejected' : null } |
  { 'shortlisted' : null };
export interface CommunicationTemplate {
  'id' : bigint,
  'subject' : string,
  'body' : string,
  'name' : string,
  'category' : string,
}
export interface Interview {
  'id' : bigint,
  'status' : InterviewStatus,
  'interviewer' : string,
  'jobId' : bigint,
  'jobTitle' : string,
  'interviewType' : InterviewType,
  'notes' : string,
  'candidateName' : string,
  'dateTime' : Time,
  'candidateId' : bigint,
}
export interface InterviewInput {
  'interviewer' : string,
  'jobId' : bigint,
  'interviewType' : InterviewType,
  'notes' : string,
  'dateTime' : Time,
  'candidateId' : bigint,
}
export type InterviewStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type InterviewType = { 'video' : null } |
  { 'phone' : null } |
  { 'onSite' : null };
export interface JobRequisition {
  'id' : bigint,
  'status' : JobStatus,
  'experienceLevel' : bigint,
  'title' : string,
  'jobType' : JobType,
  'createdAt' : Time,
  'description' : string,
  'department' : string,
  'requiredSkills' : Array<string>,
  'location' : string,
}
export type JobStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'draft' : null } |
  { 'onHold' : null };
export type JobType = { 'contract' : null } |
  { 'partTime' : null } |
  { 'fullTime' : null };
export interface OfferLetter {
  'id' : bigint,
  'status' : OfferStatus,
  'salary' : number,
  'createdAt' : Time,
  'jobId' : bigint,
  'letterText' : string,
  'clauses' : string,
  'candidateId' : bigint,
  'startDate' : Time,
}
export type OfferStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface ParsedResume {
  'previousRoles' : Array<string>,
  'education' : Array<string>,
  'experienceYears' : bigint,
  'skills' : Array<string>,
}
export interface PipelineTransition {
  'toStatus' : CandidateStatus,
  'note' : string,
  'fromStatus' : CandidateStatus,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyToJob' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateMatchScore' : ActorMethod<[bigint, bigint], bigint>,
  'createCandidate' : ActorMethod<
    [string, string, string, string, Array<string>, bigint],
    bigint
  >,
  'createInterview' : ActorMethod<
    [bigint, bigint, Time, string, InterviewType, string],
    bigint
  >,
  'createInterview2' : ActorMethod<[InterviewInput], bigint>,
  'createJob' : ActorMethod<
    [string, string, string, JobType, string, Array<string>, bigint],
    bigint
  >,
  'createOfferLetter' : ActorMethod<
    [bigint, bigint, number, Time, string],
    bigint
  >,
  'createTemplate' : ActorMethod<[string, string, string, string], bigint>,
  'deleteCandidate' : ActorMethod<[bigint], undefined>,
  'deleteInterview' : ActorMethod<[bigint], undefined>,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'deleteOfferLetter' : ActorMethod<[bigint], undefined>,
  'deleteTemplate' : ActorMethod<[bigint], undefined>,
  'getAnalytics' : ActorMethod<[], AnalyticsResult>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidate' : ActorMethod<[bigint], [] | [Candidate]>,
  'getCandidatesByJob' : ActorMethod<[bigint], Array<Candidate>>,
  'getCandidatesByStage' : ActorMethod<
    [bigint, CandidateStatus],
    Array<Candidate>
  >,
  'getInterview' : ActorMethod<[bigint], [] | [Interview]>,
  'getInterviewsByCandidate' : ActorMethod<[bigint], Array<Interview>>,
  'getJob' : ActorMethod<[bigint], [] | [JobRequisition]>,
  'getOfferLetter' : ActorMethod<[bigint], [] | [OfferLetter]>,
  'getOffersByCandidate' : ActorMethod<[bigint], Array<OfferLetter>>,
  'getTemplate' : ActorMethod<[bigint], [] | [CommunicationTemplate]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCandidates' : ActorMethod<[], Array<Candidate>>,
  'listInterviews' : ActorMethod<[], Array<Interview>>,
  'listJobs' : ActorMethod<[], Array<JobRequisition>>,
  'listOfferLetters' : ActorMethod<[], Array<OfferLetter>>,
  'listTemplates' : ActorMethod<[], Array<CommunicationTemplate>>,
  'moveCandidateStage' : ActorMethod<
    [bigint, CandidateStatus, string],
    undefined
  >,
  'parseResume' : ActorMethod<[string], ParsedResume>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCandidate' : ActorMethod<
    [bigint, string, string, string, string, Array<string>, bigint],
    undefined
  >,
  'updateInterview' : ActorMethod<
    [bigint, Time, string, InterviewType, InterviewStatus, string],
    undefined
  >,
  'updateInterview2' : ActorMethod<
    [bigint, Time, string, InterviewType, InterviewStatus, string],
    undefined
  >,
  'updateJob' : ActorMethod<
    [bigint, string, string, string, JobType, string, Array<string>, bigint],
    undefined
  >,
  'updateJobStatus' : ActorMethod<[bigint, JobStatus], undefined>,
  'updateOfferStatus' : ActorMethod<[bigint, OfferStatus], undefined>,
  'updateTemplate' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];