/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsResult {
  'topScoringCandidates' : Array<[bigint, bigint]>,
  'totalOpenJobs' : bigint,
  'totalCandidatesPerJob' : Array<[bigint, bigint]>,
  'candidatesPerStage' : Array<[string, bigint]>,
  'averageTimeToHireDays' : number,
}
export interface Candidate {
  'id' : bigint,
  'status' : CandidateStatus,
  'resume' : string,
  'pipelineLog' : Array<PipelineTransition>,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'updatedAt' : Time,
  'experienceYears' : bigint,
  'phone' : string,
  'appliedJobIds' : Array<bigint>,
  'matchScores' : Array<[bigint, bigint]>,
  'skills' : Array<string>,
}
export type CandidateStatus = { 'new' : null } |
  { 'hired' : null } |
  { 'offer' : null } |
  { 'screening' : null } |
  { 'interview' : null } |
  { 'rejected' : null } |
  { 'shortlisted' : null };
export interface CommunicationTemplate {
  'id' : bigint,
  'subject' : string,
  'body' : string,
  'name' : string,
  'category' : string,
}
export interface Interview {
  'id' : bigint,
  'status' : InterviewStatus,
  'interviewer' : string,
  'jobId' : bigint,
  'interviewType' : InterviewType,
  'notes' : string,
  'dateTime' : Time,
  'candidateId' : bigint,
}
export type InterviewStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type InterviewType = { 'video' : null } |
  { 'phone' : null } |
  { 'onSite' : null };
export interface JobRequisition {
  'id' : bigint,
  'status' : JobStatus,
  'experienceLevel' : bigint,
  'title' : string,
  'jobType' : JobType,
  'createdAt' : Time,
  'description' : string,
  'department' : string,
  'requiredSkills' : Array<string>,
  'location' : string,
}
export type JobStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'draft' : null } |
  { 'onHold' : null };
export type JobType = { 'contract' : null } |
  { 'partTime' : null } |
  { 'fullTime' : null };
export interface OfferLetter {
  'id' : bigint,
  'status' : OfferStatus,
  'salary' : number,
  'createdAt' : Time,
  'jobId' : bigint,
  'letterText' : string,
  'clauses' : string,
  'candidateId' : bigint,
  'startDate' : Time,
}
export type OfferStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface ParsedResume {
  'previousRoles' : Array<string>,
  'education' : Array<string>,
  'experienceYears' : bigint,
  'skills' : Array<string>,
}
export interface PipelineTransition {
  'toStatus' : CandidateStatus,
  'note' : string,
  'fromStatus' : CandidateStatus,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Apply a candidate to a job. Any authenticated user.
   */
  'applyToJob' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Calculate and store a match score for a candidate against a job. Any authenticated user.
   */
  'calculateMatchScore' : ActorMethod<[bigint, bigint], bigint>,
  /**
   * / Create a candidate profile. Any authenticated user (recruiter submitting on behalf).
   */
  'createCandidate' : ActorMethod<
    [string, string, string, string, Array<string>, bigint],
    bigint
  >,
  /**
   * / Create an interview record. Any authenticated user.
   */
  'createInterview' : ActorMethod<
    [bigint, bigint, Time, string, InterviewType, string],
    bigint
  >,
  /**
   * / Create a new job requisition. Admin only.
   */
  'createJob' : ActorMethod<
    [string, string, string, JobType, string, Array<string>, bigint],
    bigint
  >,
  /**
   * / Generate and store an offer letter. Any authenticated user (recruiter).
   */
  'createOfferLetter' : ActorMethod<
    [bigint, bigint, number, Time, string],
    bigint
  >,
  /**
   * / Create a communication template. Admin only.
   */
  'createTemplate' : ActorMethod<[string, string, string, string], bigint>,
  /**
   * / Delete a candidate. Admin only.
   */
  'deleteCandidate' : ActorMethod<[bigint], undefined>,
  /**
   * / Delete an interview. Admin only.
   */
  'deleteInterview' : ActorMethod<[bigint], undefined>,
  /**
   * / Delete a job requisition. Admin only.
   */
  'deleteJob' : ActorMethod<[bigint], undefined>,
  /**
   * / Delete an offer letter. Admin only.
   */
  'deleteOfferLetter' : ActorMethod<[bigint], undefined>,
  /**
   * / Delete a communication template. Admin only.
   */
  'deleteTemplate' : ActorMethod<[bigint], undefined>,
  /**
   * / Get recruiter analytics. Any authenticated user.
   */
  'getAnalytics' : ActorMethod<[], AnalyticsResult>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get a single candidate. Any authenticated user.
   */
  'getCandidate' : ActorMethod<[bigint], [] | [Candidate]>,
  /**
   * / Get candidates by job ID. Any authenticated user.
   */
  'getCandidatesByJob' : ActorMethod<[bigint], Array<Candidate>>,
  /**
   * / Get candidates by pipeline stage for a given job. Any authenticated user.
   */
  'getCandidatesByStage' : ActorMethod<
    [bigint, CandidateStatus],
    Array<Candidate>
  >,
  /**
   * / Get a single interview. Any authenticated user.
   */
  'getInterview' : ActorMethod<[bigint], [] | [Interview]>,
  /**
   * / List interviews for a candidate. Any authenticated user.
   */
  'getInterviewsByCandidate' : ActorMethod<[bigint], Array<Interview>>,
  /**
   * / Get a single job requisition. Any authenticated user.
   */
  'getJob' : ActorMethod<[bigint], [] | [JobRequisition]>,
  /**
   * / Get an offer letter. Any authenticated user.
   */
  'getOfferLetter' : ActorMethod<[bigint], [] | [OfferLetter]>,
  /**
   * / List offer letters for a candidate. Any authenticated user.
   */
  'getOffersByCandidate' : ActorMethod<[bigint], Array<OfferLetter>>,
  /**
   * / Get a single template. Any authenticated user.
   */
  'getTemplate' : ActorMethod<[bigint], [] | [CommunicationTemplate]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List all candidates. Any authenticated user.
   */
  'listCandidates' : ActorMethod<[], Array<Candidate>>,
  /**
   * / List all job requisitions. Any authenticated user.
   */
  'listJobs' : ActorMethod<[], Array<JobRequisition>>,
  /**
   * / List all templates. Any authenticated user.
   */
  'listTemplates' : ActorMethod<[], Array<CommunicationTemplate>>,
  /**
   * / Move a candidate to the next pipeline stage. Recruiter (user) or Admin only.
   */
  'moveCandidateStage' : ActorMethod<
    [bigint, CandidateStatus, string],
    undefined
  >,
  /**
   * / Parse a resume text and extract structured data. No auth required (public utility).
   */
  'parseResume' : ActorMethod<[string], ParsedResume>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Update candidate details. Any authenticated user.
   */
  'updateCandidate' : ActorMethod<
    [bigint, string, string, string, string, Array<string>, bigint],
    undefined
  >,
  /**
   * / Update an interview record. Any authenticated user.
   */
  'updateInterview' : ActorMethod<
    [bigint, Time, string, InterviewType, InterviewStatus, string],
    undefined
  >,
  /**
   * / Update an existing job requisition. Admin only.
   */
  'updateJob' : ActorMethod<
    [bigint, string, string, string, JobType, string, Array<string>, bigint],
    undefined
  >,
  /**
   * / Update job status. Admin only.
   */
  'updateJobStatus' : ActorMethod<[bigint, JobStatus], undefined>,
  /**
   * / Update offer letter status. Any authenticated user.
   */
  'updateOfferStatus' : ActorMethod<[bigint, OfferStatus], undefined>,
  /**
   * / Update a communication template. Admin only.
   */
  'updateTemplate' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];